name: Send Email Notification

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # This checks out your repository's code

      - name: Send Email
        uses: dawidd6/action-send-mail@v3  # Correct external action
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Git Push Notification: danielbiton342/sela-test"
          body: |
            A new code push was made to the repository.

            - **Pushed by**: ${{ github.actor }}
            - **Repository**: danielbiton342/sela-test
            - **Commit hash**: ${{ github.sha }}

            Check the repository for more details.

          to: your-email@example.com
          from: ${{ secrets.EMAIL_USERNAME }}
