name: Send Email Notification

on:
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Send Test Email
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: ${{ secrets.MAIL_CONNECTION }}
          subject: "Test Email"
          body: "This is a test email from GitHub Actions."
          to: danielbit114@gmail.com
          from: danielbit114@gmail.com
