name: Send Email Notification

on:
  workflow_dispatch:


jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # This checks out your repository's code

      - name: Send Email
        uses: dawidd6/action-send-mail@v3  # Use this action to send the email
        with:
          server_address: smtp.gmail.com  # SMTP server for Gmail
          server_port: 465                # Port (use 465 for SSL)
          username: ${{ secrets.EMAIL_USERNAME }}  # Your email address stored in secrets
          password: ${{ secrets.EMAIL_PASSWORD }}  # Your email password stored in secrets
          subject: "Git Push Notification: ${{ github.repository }}"
          body: |
            A new code push was made to the repository:

            - **Pushed by**: ${{ github.actor }}
            - **Repository**: ${{ github.repository }}
            - **Commit hash**: ${{ github.sha }}

            Check the repository for more details.

          to: danielbit114@gmail.com  # Replace with your email address
          from: ${{ secrets.EMAIL_USERNAME }}  # This is the sender's email address (same as the username)

      - name: Log Details
        run: |
          echo "Pushed by: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
          echo "Commit hash: ${{ github.sha }}"

