name: Send Email Notification

on:
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # This checks out your repository's code

      - name: Send Email
        uses: dawidd6/action-send-mail@v3  # Use this action to send the email
        with:
          # Use the connection URL for sending email with secrets stored securely
          connection_url: ${{ secrets.MAIL_CONNECTION }}
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: "Git Push Notification: ${{ github.repository }}"
          body: |
            A new code push was made to the repository:

            - **Pushed by**: ${{ github.actor }}
            - **Repository**: ${{ github.repository }}
            - **Commit hash**: ${{ github.sha }}

            Check the repository for more details.
          to: danielbit114@gmail.com  # Your recipient email address
          from: ${{ secrets.EMAIL_USERNAME }}  # Sender's email address (same as the username)
         

      - name: Log Details
        run: |
          echo "Pushed by: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
          echo "Commit hash: ${{ github.sha }}"


