name: Send Email Notification

on:
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # This checks out your repository's code

      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: ${{ secrets.MAIL_CONNECTION }}  # Use the connection string stored in secrets
          server_address: smtp.gmail.com                  # SMTP server address
          server_port: 465                                # Explicitly specify the port (465 for SMTPS)
          subject: "Git Push Notification: ${{ github.repository }}"
          body: |
            A new code push was made to the repository:
            - **Pushed by**: ${{ github.actor }}
            - **Repository**: ${{ github.repository }}
            - **Commit hash**: ${{ github.sha }}
            Check the repository for more details.
          to: danielbit114@gmail.com                      # Recipient email address
          from: danielbit114@gmail.com                      # Sender's email address (same as username)

